# Generated by Django 3.1.3 on 2020-11-16 16:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=25)),
                ('nazwisko', models.CharField(max_length=30)),
                ('nr_gabinetu', models.PositiveSmallIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('specjalizacja', models.PositiveSmallIntegerField(choices=[(4, 'Ginekolog'), (1, 'Alergolog'), (3, 'Laryngolog'), (2, 'Dermatolog'), (0, 'Pediatra')], default=0)),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarze',
            },
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('imie', models.CharField(max_length=25)),
                ('nazwisko', models.CharField(max_length=30)),
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nr_tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Numer kontaktowy lub do rodzica', max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Pacjent',
                'verbose_name_plural': 'Pacjenci',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(blank=True, max_length=25)),
                ('nazwisko', models.CharField(blank=True, max_length=30)),
                ('pesel', models.CharField(blank=True, max_length=11, unique=True)),
                ('nr_tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Numer kontaktowy lub do rodzica', max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wizyty', models.DateField(default=django.utils.timezone.now)),
                ('godzina_wizyty', models.TimeField()),
                ('dodatkowe_inf', models.TextField(blank=True, max_length=300, null=True)),
                ('rodzaj_wizyty', models.SmallIntegerField(blank=True, choices=[(0, 'Teleporada'), (1, 'Normalna wizyta')])),
                ('id_lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rej.lekarz')),
                ('id_pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rej.profile')),
            ],
            options={
                'verbose_name': 'Wizyta',
                'verbose_name_plural': 'Wizyty',
            },
        ),
    ]
