# Generated by Django 3.1.3 on 2020-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='specjalizacja',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pediatra'), (4, 'Ginekolog'), (3, 'Laryngolog'), (2, 'Dermatolog'), (1, 'Alergolog')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pesel',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='rodzaj_wizyty',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Normalna wizyta'), (0, 'Teleporada')]),
        ),
    ]
