# Generated by Django 3.1.3 on 2020-11-17 20:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=30)),
                ('office_nr', models.PositiveSmallIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('specialization', models.PositiveSmallIntegerField(choices=[(2, 'Dermatolog'), (0, 'Pediatra'), (4, 'Ginekolog'), (3, 'Laryngolog'), (1, 'Alergolog')], default=0)),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarze',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('visit_time', models.TimeField()),
                ('add_inf', models.TextField(blank=True, max_length=300, null=True)),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, 'Teleporada'), (1, 'Normalna wizyta')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rej.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wizyta',
                'verbose_name_plural': 'Wizyty',
            },
        ),
    ]
