# Generated by Django 3.1.3 on 2020-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0003_auto_20201116_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='specjalizacja',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Ginekolog'), (0, 'Pediatra'), (2, 'Dermatolog'), (1, 'Alergolog'), (3, 'Laryngolog')], default=0),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='godzina_wizyty',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='rodzaj_wizyty',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Normalna wizyta'), (0, 'Teleporada')]),
        ),
    ]
