# Generated by Django 3.1.3 on 2020-11-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0004_auto_20201121_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Ginekolog'), (1, 'Alergolog'), (2, 'Dermatolog'), (3, 'Laryngolog'), (0, 'Pediatra')], default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Teleporada'), (1, 'Normalna wizyta')], default=0),
        ),
    ]
