# Generated by Django 3.1.3 on 2020-11-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0004_auto_20201116_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='specjalizacja',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Laryngolog'), (4, 'Ginekolog'), (0, 'Pediatra'), (1, 'Alergolog'), (2, 'Dermatolog')], default=0),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='godzina_wizyty',
            field=models.DateField(),
        ),
    ]
