# Generated by Django 3.1.3 on 2020-11-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0005_auto_20201121_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Dermatolog'), (0, 'Pediatra'), (1, 'Alergolog'), (3, 'Laryngolog'), (4, 'Ginekolog')], default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Normalna wizyta'), (0, 'Teleporada')], default=0),
        ),
    ]
