# Generated by Django 3.1.3 on 2020-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0005_auto_20201116_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='specjalizacja',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Ginekolog'), (3, 'Laryngolog'), (2, 'Dermatolog'), (1, 'Alergolog'), (0, 'Pediatra')], default=0),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='godzina_wizyty',
            field=models.TimeField(),
        ),
    ]
