# Generated by Django 3.1.3 on 2020-11-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0006_auto_20201121_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Dermatolog'), (4, 'Ginekolog'), (0, 'Pediatra'), (1, 'Alergolog'), (3, 'Laryngolog')], default=0),
        ),
    ]
