# Generated by Django 3.1.3 on 2020-11-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0007_auto_20201121_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alergolog'), (3, 'Laryngolog'), (2, 'Dermatolog'), (4, 'Ginekolog'), (0, 'Pediatra')], default=0),
        ),
    ]
