# Generated by Django 3.1.3 on 2020-11-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0008_auto_20201128_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alergolog'), (3, 'Laryngolog'), (0, 'Pediatra'), (2, 'Dermatolog'), (4, 'Ginekolog')], default=0),
        ),
    ]
