# Generated by Django 3.1.3 on 2020-11-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0009_auto_20201128_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Teleporada'), (1, 'Normalna wizyta')], default=0),
        ),
    ]
