# Generated by Django 3.1.3 on 2020-11-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0010_auto_20201128_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pediatra'), (1, 'Alergolog'), (2, 'Dermatolog'), (3, 'Laryngolog'), (4, 'Ginekolog')], default=0),
        ),
    ]
