# Generated by Django 3.1.3 on 2020-11-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0012_auto_20201128_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Dermatolog'), (3, 'Laryngolog'), (1, 'Alergolog'), (0, 'Pediatra'), (4, 'Ginekolog')], default=0),
        ),
    ]
