# Generated by Django 3.1.3 on 2020-11-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0013_auto_20201128_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Ginekolog'), (0, 'Pediatra'), (2, 'Dermatolog'), (3, 'Laryngolog'), (1, 'Alergolog')], default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Normalna wizyta'), (0, 'Teleporada')], default=0),
        ),
    ]
