# Generated by Django 3.1.3 on 2020-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0014_auto_20201128_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Laryngolog'), (4, 'Ginekolog'), (2, 'Dermatolog'), (0, 'Pediatra'), (1, 'Alergolog')], default=0),
        ),
    ]
