# Generated by Django 3.1.3 on 2020-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0015_auto_20201128_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Dermatolog'), (3, 'Laryngolog'), (0, 'Pediatra'), (1, 'Alergolog'), (4, 'Ginekolog')], default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Teleporada'), (1, 'Normalna wizyta')], default=0),
        ),
    ]
