# Generated by Django 3.1.3 on 2020-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0017_auto_20201128_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alergolog'), (2, 'Dermatolog'), (4, 'Ginekolog'), (0, 'Pediatra'), (3, 'Laryngolog')], default=0),
        ),
    ]
