# Generated by Django 3.1.3 on 2020-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej', '0020_auto_20201128_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Laryngolog'), (0, 'Pediatra'), (1, 'Alergolog'), (2, 'Dermatolog'), (4, 'Ginekolog')], default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Normalna wizyta'), (0, 'Teleporada')], default=0),
        ),
    ]
